
OBJS=\
	mod_cisco_ac.o \
	mod_cisco_wtp.o \
	cisco_actions_ac.o \
	cisco_actions_wtp.o \
	cisco_out_ap_timesync.o \
	cisco_in_wtp_descriptor.o \
	cisco_out_ac_descriptor.o \
	cisco_out_wtp_descriptor.o \
	cisco_out_telnet_ssh.o \
	cisco_in_ac_descriptor.o\
	cisco80211.o \
	cisco_out_board_data_options.o \
	cisco_in_radio_administrative_state.o \
	cisco_in_spam_vendor_specific.o \
	cisco_in_telnet_ssh.o \
	cisco_items.o \
	cisco80211_in_mac_operation.o \
	cisco80211_in_wtp_radio_configuration.o \
	cisco80211_out_wtp_radio_configuration.o \
	cisco_out_manager_ip_addr.o \
	cisco_out_ac_ipv4_list.o \
	cisco_out_capwap_up.o \
	cisco_in_add_wlan.o \
	cisco_out_wtp_administrative_state.o \
	cisco_out_radio_operational_state.o \
	cisco_in_radio_operational_state.o \
	cisco_out_wtp_operational_state.o

#	cisco_out_radio_administrative_state.o \

	

NAME=libcisco.a

include ../Mod.mak


