
OBJS=\
	mod_cisco_ac.o \
	mod_cisco_wtp.o \
	cisco_actions_ac.o \
	cisco_actions_wtp.o \
	cisco_out_ap_timesync.o \
	cisco_in_wtp_descriptor.o \
	cisco_out_ac_descriptor.o \
	cisco_out_wtp_descriptor.o \
	cisco_in_ac_descriptor.o\
	cisco80211.o \
	cisco_in_radio_administrative_state.o
	
	

NAME=libcisco.a

include ../Mod.mak


