language: cpp
compiler:
  - clang
  - gcc
sudo: require
dist: trusty
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get -qq install g++-4.9 libstdc++-4.9-dev
  - sudo apt-get -qq install cmake lua5.2 libnl-genl-3-dev
  - sudo apt-get -qq install nettle-dev libgnutls28-dev libssl-dev
  - sudo apt-get -qq install libconfuse-dev libsqlite3-dev
  - $CC --version
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - $CC --version
  - $CXX --version
script:
  - make
  - cd src
  - cd ac 
  - ./actube &
  - cd ..
  - cd wtp
  - ./wtp &
