
OBJS=\
	mod_fortinet_ac.o \
	mod_fortinet_wtp.o \
	fortinet_actions_ac.o \
	fortinet_actions_wtp.o \
#	cisco_out_ap_timesync.o \
#	cisco_in_wtp_descriptor.o \
#	cisco_out_ac_descriptor.o \
#	cisco_out_wtp_descriptor.o \
#	cisco_in_ac_descriptor.o\
#	cisco80211.o \
#	cisco_in_radio_administrative_state.o \
#	cisco_out_board_data_options.o


NAME=libfortinet.a

include ../Mod.mak


