include ../../Defs.mak


OBJS=\
	mod_capwap80211.o \
	capwap80211_messages.o \


LIBDIR		:= ../../../lib
LIBARCHDIR	:= $(LIBDIR)/$(ARCH)
OBJDIR		:= ../../../obj/mod_capwap80211/$(ARCH)
SNAME		:= $(LIBARCHDIR)/libmod_capwap80211.a
DNAME		:= $(LIBARCHDIR)/mod_capwap80211.so
MODNAME		:= $(LIBDIR)/mod_capwap80211.so
SLIBS		:= -lcw

include ../Mod.mak


