#ifndef __CAPWAP_ITEMS_H
#define __CAPWAP_ITEMS_H

enum capwap_items {
	CW_ITEM_NONE=0,
	CW_ITEM_DISCOVERY_TYPE,
	CW_ITEM_WTP_NAME,
	CW_ITEM_WTP_BOARD_VENDOR,
	CW_ITEM_WTP_BOARD_MODELNO,
	CW_ITEM_WTP_BOARD_MACADDRESS,
	CW_ITEM_WTP_BOARD_ID,
	CW_ITEM_WTP_BOARD_REVISION,
	CW_ITEM_WTP_BOARD_SERIALNO,
	CW_ITEM_WTP_MAC_TYPE,
	CW_ITEM_WTP_FRAME_TUNNEL_MODE,
	CW_ITEM_WTP_RADIOS_IN_USE,
	CW_ITEM_WTP_MAX_RADIOS,
	CW_ITEM_WTP_HARDWARE_VENDOR,
	CW_ITEM_WTP_HARDWARE_VERSION,
	CW_ITEM_WTP_SOFTWARE_VENDOR,
	CW_ITEM_WTP_SOFTWARE_VERSION,
	CW_ITEM_WTP_BOOTLOADER_VENDOR,
	CW_ITEM_WTP_BOOTLOADER_VERSION,
	CW_ITEM_WTP_OTHERSOFTWARE_VENDOR,
	CW_ITEM_WTP_OTHERSOFTWARE_VERSION,

	CW_ITEM_AC_NAME,
	CW_ITEM_AC_DESCRIPTOR,
	CW_ITEM_RESULT_CODE,
	CW_ITEM_AC_STATUS,

	CW_ITEM_AC_HARDWARE_VERSION,
	CW_ITEM_AC_SOFTWARE_VERSION,

	CW_ITEM_AC_IP_LIST,
	CW_ITEM_CAPWAP_CONTROL_IP_LIST,

	CW_ITEM_LOCATION_DATA,
	CW_ITEM_SESSION_ID,

	

};


#endif
