#ifndef __CAPWAP_ITEMS_H
#define __CAPWAP_ITEMS_H

enum capwap_items {
	CW_ITEM_NONE=0,
	CW_ITEM_IDLE_TIMEOUT,
	CW_ITEM_DISCOVERY_TYPE,
	CW_ITEM_WTP_NAME,
	CW_ITEM_WTP_BOARD_VENDOR,
	CW_ITEM_WTP_BOARD_MODELNO,
	CW_ITEM_WTP_BOARD_MACADDRESS,
	CW_ITEM_WTP_BOARD_ID,
	CW_ITEM_WTP_BOARD_REVISION,
	CW_ITEM_WTP_BOARD_SERIALNO,
	CW_ITEM_WTP_MAC_TYPE,
	CW_ITEM_WTP_FRAME_TUNNEL_MODE,
	CW_ITEM_WTP_RADIOS_IN_USE,
	CW_ITEM_WTP_MAX_RADIOS,
	CW_ITEM_WTP_HARDWARE_VENDOR,
	CW_ITEM_WTP_HARDWARE_VERSION,
	CW_ITEM_WTP_SOFTWARE_VENDOR,
	CW_ITEM_WTP_SOFTWARE_VERSION,
	CW_ITEM_WTP_BOOTLOADER_VENDOR,
	CW_ITEM_WTP_BOOTLOADER_VERSION,
	CW_ITEM_WTP_OTHERSOFTWARE_VENDOR,
	CW_ITEM_WTP_OTHERSOFTWARE_VERSION,
	CW_ITEM_WTP_BOARD_DATA,
	CW_ITEM_WTP_DESCRIPTOR,
	CW_ITEM_CAPWAP_TIMERS,

	CW_ITEM_AC_NAME,
	CW_ITEM_AC_DESCRIPTOR,
	CW_ITEM_RESULT_CODE,
	CW_ITEM_AC_STATUS,

	CW_ITEM_AC_HARDWARE_VERSION,
	CW_ITEM_AC_SOFTWARE_VERSION,

	CW_ITEM_AC_IP_LIST,
	CW_ITEM_CAPWAP_CONTROL_IP_ADDRESS_LIST,

	CW_ITEM_LOCATION_DATA,
	CW_ITEM_SESSION_ID,
	
	CW_ITEM_AC_TIMESTAMP,
	CW_ITEM_STATISTICS_TIMER,
	CW_ITEM_WTP_REBOOT_STATISTICS,
	CW_ITEM_IMAGE_IDENTIFIER,
	CW_ITEM_AC_HASH_VALUE,



	/* CIPWAP and Cisco */
	CW_ITEM_WTP_GROUP_NAME,
	

	/* Other Items */
	CW_ITEM_AC_IMAGE_DIR,		/* Path where WTP images are stored */
	CW_ITEM_IMAGE_FILENAME,		/* Full path of image filename */
	CW_ITEM_DISCOVERIES,
	CW_ITEM_AC_PRIO_LIST,		/* AC Name with Priority list */
	
	/** FILE handle for uploading and downloading images  */
	CW_ITEM_IMAGE_FILEHANDLE,	

	CW_ITEM_RADIO_CFG,

};


#endif
