
enum capwap_items {
	CW_ITEM_NONE=0,
	CW_ITEM_DISCOVERY_TYPE,
	CW_ITEM_WTP_NAME
	CW_ITEM_WTP_BOARD_VENDOR,
	CW_ITEM_WTP_BOARD_MODELNO,
	CW_ITEM_WTP_BOARD_MACADDRESS,
	CW_ITEM_WTP_BOARD_ID,
	CW_ITEM_WTP_BOARD_REVISISON,
	CW_ITEM_WTP_BOARD_SERIALNO

};
