

struct cw_strlist capwap_strings_elem[] = {

 CW_ELEM_AC_DESCRIPTOR,"AC Descriptor",
 CW_ELEM_AC_IPV4_LIST,"AC IPv4 List",
 CW_ELEM_AC_IPV6_LIST,"AC IPv6 List",
 CW_ELEM_AC_NAME,"AC Name",
 CW_ELEM_AC_NAME_WITH_PRIORITY,"AC Name with Priority",
 CW_ELEM_AC_NAME_WITH_INDEX,"AC Name width Index",	
 CW_ELEM_AC_TIMESTAMP,"AC Timestamp",
 CW_ELEM_ADD_MAC_ACL_ENTRY,"Add MAC ACL Entry",
 CW_ELEM_ADD_STATION,"Add Station",
 CW_ELEM_RESERVED_9,"Reserved 9",
 CW_ELEM_CONTROL_IPV4_ADDRESS,"Control IPv4 Address",
 CWMSGELEM_CONTROL_IPV6_ADDRESS,"Controll IPv6 Address",
 CWMSGELEM_CAPWAP_LOCAL_IPV4_ADDRESS		30
 CWMSGELEM_CAPWAP_LOCAL_IPV6_ADDRESS		50
 CW_ELEM_CAPWAP_TIMERS				12
 CW_ELEM_CAPWAP_TRANSPORT_PROTOCOL		51     /* not in draft 7 */
 CW_ELEM_DATA_TRANSFER_DATA			13
 CW_ELEM_DATA_TRANSFER_MODE			14
 CW_ELEM_DECRYPTION_ERROR_REPORT			15
 CW_ELEM_DECRYPTION_ERROR_REPORT_PERIOD		16
 CW_ELEM_DELETE_MAC_ACL_ENTRY			17
 CW_ELEM_DELETE_STATION				18
 CW_ELEM_RESEERVED_19				19
 CW_ELEM_DISCOVERY_TYPE				20
 CW_ELEM_DUPLICATE_IPV4_ADDRESS			21
 CW_ELEM_DUPLICATE_IPV6_ADRESS			22
 CWMSGELEM_ECN_SUPPORT				53
 CW_ELEM_IDLE_TIMEOUT				23
 CW_ELEM_IMAGE_DATA				24
 CW_ELEM_IMAGE_IDENTIFIER			25
 CW_ELEM_IMAGE_INFORMATION			26
 CW_ELEM_INITIATE_DOWNLOAD			27
 CWMSGELEM_LOCATION_DATA				28
 CWMSGELEM_MAXIMUM_MESSAGE_LENGTH		29
 CWMSGELEM_MTU_DISCOVERY_PADDING			52
 CWMSGELEM_RADIO_ADMINISTRATIVE_STATE		31
 CW_ELEM_RADIO_OPERATIONAL_STATE			32
 CW_ELEM_RESULT_CODE				33
 CW_ELEM_RETURNED_MESSAGE_ELEMENT		34
 CW_ELEM_SESSION_ID				35
 CW_ELEM_STATISTICS_TIMER			36
 CW_ELEM_VENDOR_SPECIFIC_PAYLOAD			37
 CW_ELEM_WTP_BOARD_DATA				38
 CW_ELEM_WTP_DESCRIPTOR				39
 CW_ELEM_WTP_FALLBACK				40
 CW_ELEM_WTP_FRAME_TUNNEL_MODE			41
 CW_ELEM_RESERVED_42				42
 CW_ELEM_RESERVED_43				43
 CW_ELEM_WTP_MAC_TYPE				44
 CW_ELEM_WTP_NAME				45
 CW_ELEM_RESERVED_46				46
 CW_ELEM_WTP_RADIO_STATISTICS			47
 CWMSGELEM_WTP_REBOOT_STATISTICS			48
 CW_ELEM_WTP_STATIC_IP_ADDRESS_INFORMATION	49
 CW_ELEM_WTP_STATIC_IP_ADDR_INFO			49


/* Cisco's CAPWAP definitions (CAPWAP draft 7) */
 CW_ELEM_WTP_IPV4_IP_ADDRESS			42
 CW_ELEM_WTP_IPV6_IP_ADDRESS			43



}

